# Generated by Django 5.2.7 on 2025-11-25 11:52

import users_auth.custom_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APICredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(help_text="API provider name (e.g., 'dhan', 'zerodha')", max_length=50, unique=True)),
                ('api_key', users_auth.custom_fields.EncryptedField(blank=True, help_text='API Key (encrypted)', max_length=255, null=True)),
                ('api_secret', users_auth.custom_fields.EncryptedField(blank=True, help_text='API Secret (encrypted)', max_length=255, null=True)),
                ('access_token', users_auth.custom_fields.EncryptedField(blank=True, help_text='Access token (encrypted)', max_length=512, null=True)),
                ('totp_secret', users_auth.custom_fields.EncryptedField(blank=True, help_text='TOTP secret key (encrypted)', max_length=255, null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Additional metadata (createTime, expiryTime, etc.)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'API Credential',
                'verbose_name_plural': 'API Credentials',
                'ordering': ['provider'],
            },
        ),
    ]
