# Generated by Django 5.2.7 on 2025-10-25 16:57

import django.db.models.deletion
import users_auth.custom_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='kite_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('kite_username', users_auth.custom_fields.EncryptedField(blank=True, help_text='Kite login ID (encrypted).', max_length=255)),
                ('kite_pwd', users_auth.custom_fields.EncryptedField(blank=True, help_text='Kite password (encrypted).', max_length=255)),
                ('totp_key', users_auth.custom_fields.EncryptedField(blank=True, help_text='TOTP secret key (encrypted).', max_length=255, null=True)),
                ('access_token', users_auth.custom_fields.EncryptedField(blank=True, help_text='The latest valid Kite Connect access token.', max_length=512)),
            ],
            options={
                'verbose_name': 'Kite User Profile',
            },
        ),
        migrations.CreateModel(
            name='Trades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_id', models.CharField(db_index=True, help_text='Unique trade identifier from the exchange (fill ID).', max_length=50, unique=True)),
                ('order_id', models.CharField(db_index=True, max_length=50)),
                ('exchange_order_id', models.CharField(max_length=50)),
                ('tradingsymbol', models.CharField(db_index=True, max_length=50)),
                ('instrument_token', models.CharField(max_length=50)),
                ('exchange', models.CharField(max_length=10)),
                ('product', models.CharField(max_length=10)),
                ('quantity', models.IntegerField(help_text="The executed quantity (the 'fill').")),
                ('average_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('transaction_type', models.CharField(max_length=12)),
                ('fill_timestamp', models.DateTimeField(db_index=True, help_text='The precise execution time of the trade (the fill time).')),
                ('order_timestamp', models.DateTimeField(blank=True, null=True)),
                ('exchange_timestamp', models.DateTimeField(blank=True, null=True)),
                ('tag', models.CharField(blank=True, help_text='Optional user-defined tag.', max_length=255, null=True)),
                ('user', models.ForeignKey(help_text='The user who executed this trade.', on_delete=django.db.models.deletion.CASCADE, related_name='trades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Trades',
                'indexes': [models.Index(fields=['tradingsymbol', 'fill_timestamp'], name='users_auth__trading_67869f_idx')],
                'unique_together': {('trade_id', 'user')},
            },
        ),
    ]
