# Generated by Django 5.2.7 on 2025-10-27 04:58

import users_auth.custom_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='kite_api_key',
            field=users_auth.custom_fields.EncryptedField(blank=True, help_text="The application's Kite API Key (encrypted).", max_length=64),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='kite_api_secret',
            field=users_auth.custom_fields.EncryptedField(blank=True, help_text="The application's Kite API Secret (encrypted).", max_length=128),
        ),
    ]
