# Generated by Django 5.2.7 on 2025-10-31 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth', '0002_userprofile_kite_api_key_userprofile_kite_api_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='trades',
            name='account_id',
            field=models.CharField(db_index=True, default=12345678, help_text='The trading account ID associated with the trade (e.g., Zerodha Client ID).', max_length=50),
            preserve_default=False,
        ),
    ]
